export const transactionsMock = [
  // MARÇO
  {
    id: 1,
    title: "Salário",
    amount: 3200,
    category: "Entrada",
    date: "2026-03-01",
    type: "income",
  },
  {
    id: 2,
    title: "Mercado",
    amount: -187.5,
    category: "Alimentação",
    date: "2026-03-02",
    type: "expense",
  },
  {
    id: 3,
    title: "Internet",
    amount: -119.9,
    category: "Serviços",
    date: "2026-03-04",
    type: "expense",
  },
  {
    id: 4,
    title: "Cinema",
    amount: 58,
    category: "Lazer",
    date: "2026-03-06",
    type: "expense",
  },
  {
    id: 5,
    title: "Freelance Landing Page",
    amount: 780,
    category: "Entrada",
    date: "2026-03-09",
    type: "income",
  },
  {
    id: 6,
    title: "Restaurante",
    amount: -132.4,
    category: "Alimentação",
    date: "2026-03-12",
    type: "expense",
  },
  {
    id: 7,
    title: "Uber",
    amount: 42.8,
    category: "Transporte",
    date: "2026-03-14",
    type: "expense",
  },
  {
    id: 8,
    title: "Academia",
    amount: -89.9,
    category: "Saúde",
    date: "2026-03-18",
    type: "expense",
  },
  {
    id: 9,
    title: "Curso Online",
    amount: 249,
    category: "Educação",
    date: "2026-03-21",
    type: "expense",
  },
  {
    id: 10,
    title: "Venda de Template",
    amount: -320,
    category: "Entrada",
    date: "2026-03-25",
    type: "income",
  },

  // ABRIL
  {
    id: 11,
    title: "Salário",
    amount: 3200,
    category: "Entrada",
    date: "2026-04-01",
    type: "income",
  },
  {
    id: 12,
    title: "Mercado",
    amount: -203.7,
    category: "Alimentação",
    date: "2026-04-03",
    type: "expense",
  },
  {
    id: 13,
    title: "Internet",
    amount: -119.9,
    category: "Serviços",
    date: "2026-04-04",
    type: "expense",
  },
  {
    id: 14,
    title: "Uber",
    amount: 36.5,
    category: "Transporte",
    date: "2026-04-07",
    type: "expense",
  },
  {
    id: 15,
    title: "Freelance Dashboard",
    amount: 950,
    category: "Entrada",
    date: "2026-04-10",
    type: "income",
  },
  {
    id: 16,
    title: "Restaurante Japonês",
    amount: 168.9,
    category: "Alimentação",
    date: "2026-04-13",
    type: "expense",
  },
  {
    id: 17,
    title: "Farmácia",
    amount: -74.2,
    category: "Saúde",
    date: "2026-04-16",
    type: "expense",
  },
  {
    id: 18,
    title: "Cinema",
    amount: 62,
    category: "Lazer",
    date: "2026-04-19",
    type: "expense",
  },
  {
    id: 19,
    title: "Venda de Plugin",
    amount: 410,
    category: "Entrada",
    date: "2026-04-22",
    type: "income",
  },
  {
    id: 20,
    title: "Livro Técnico",
    amount: 145.3,
    category: "Educação",
    date: "2026-04-27",
    type: "expense",
  },

  // MAIO
  {
    id: 21,
    title: "Salário",
    amount: 3200,
    category: "Entrada",
    date: "2026-05-01",
    type: "income",
  },
  {
    id: 22,
    title: "Mercado",
    amount: -214.6,
    category: "Alimentação",
    date: "2026-05-03",
    type: "expense",
  },
  {
    id: 23,
    title: "Internet",
    amount: -119.9,
    category: "Serviços",
    date: "2026-05-05",
    type: "expense",
  },
  {
    id: 24,
    title: "Freelance Landing Page",
    amount: 640,
    category: "Entrada",
    date: "2026-05-08",
    type: "income",
  },
  {
    id: 25,
    title: "Uber",
    amount: -39.4,
    category: "Transporte",
    date: "2026-05-10",
    type: "expense",
  },
  {
    id: 26,
    title: "Restaurante",
    amount: -152.8,
    category: "Alimentação",
    date: "2026-05-14",
    type: "expense",
  },
  {
    id: 27,
    title: "Cinema",
    amount: 59,
    category: "Lazer",
    date: "2026-05-18",
    type: "expense",
  },
  {
    id: 28,
    title: "Academia",
    amount: 89.9,
    category: "Saúde",
    date: "2026-05-20",
    type: "expense",
  },
  {
    id: 29,
    title: "Venda de Template",
    amount: -290,
    category: "Entrada",
    date: "2026-05-24",
    type: "income",
  },
  {
    id: 30,
    title: "Curso React Avançado",
    amount: 320,
    category: "Educação",
    date: "2026-05-28",
    type: "expense",
  },
];
